window.GRAND_QUIZ_CATEGORIES = [
  'Animaux',
  'Années 80, 90 & 2000',
  'Arts & peinture',
  'Cinéma & TV',
  'Corps humain',
  'Cuisine',
  'Culture générale',
  'Dessins animés',
  'France',
  'Géographie',
  'Histoire',
  'Insolite',
  'Inventions & découvertes',
  'Jeux vidéo',
  'Langue française',
  'Littérature',
  'Logique & devinettes',
  'Monde & cultures',
  'Musique',
  'Mythologie',
  'Nature & environnement',
  'Numérique',
  'Provence',
  'Sciences',
  'Sport',
];

window.GRAND_QUIZ_QUESTIONS = [
  {id:'geo1',category:'Géographie',difficulty:'Facile',type:'mcq',question:'Quelle est la capitale de l’Italie ?',options:['Madrid','Rome','Lisbonne','Athènes'],answer:1,explanation:'Rome est la capitale de l’Italie.'},
  {id:'geo2',category:'Géographie',difficulty:'Facile',type:'mcq',question:'Quel océan borde la côte ouest de la France ?',options:['Océan Pacifique','Océan Atlantique','Océan Indien','Océan Arctique'],answer:1,explanation:'La façade ouest de la France métropolitaine donne sur l’océan Atlantique.'},
  {id:'geo3',category:'Géographie',difficulty:'Moyen',type:'mcq',question:'Dans quel pays se trouve la ville de Marrakech ?',options:['Tunisie','Égypte','Maroc','Algérie'],answer:2,explanation:'Marrakech est l’une des grandes villes du Maroc.'},
  {id:'geo4',category:'Géographie',difficulty:'Moyen',type:'numeric',question:'Combien y a-t-il de continents dans le modèle le plus couramment enseigné en France ?',answer:6,unit:'continents',explanation:'En France, on enseigne généralement 6 continents : Afrique, Amérique, Antarctique, Asie, Europe et Océanie.'},
  {id:'fr1',category:'France',difficulty:'Facile',type:'mcq',question:'Quelle couleur n’apparaît pas sur le drapeau français ?',options:['Bleu','Blanc','Rouge','Vert'],answer:3,explanation:'Le drapeau français est bleu, blanc et rouge.'},
  {id:'fr2',category:'France',difficulty:'Moyen',type:'mcq',question:'Quel fleuve traverse Paris ?',options:['La Loire','Le Rhône','La Seine','La Garonne'],answer:2,explanation:'Paris est traversée par la Seine.'},
  {id:'fr3',category:'France',difficulty:'Moyen',type:'truefalse',question:'Le Mont-Saint-Michel se trouve en Normandie.',answer:true,explanation:'Le Mont-Saint-Michel est situé dans le département de la Manche, en Normandie.'},
  {id:'prov1',category:'Provence',difficulty:'Facile',type:'mcq',question:'Quelle plante violette est emblématique de la Provence ?',options:['La lavande','Le muguet','La tulipe','L’orchidée'],answer:0,explanation:'La lavande est l’un des symboles les plus connus de la Provence.'},
  {id:'prov2',category:'Provence',difficulty:'Moyen',type:'mcq',question:'Dans quel département se trouve Manosque ?',options:['Var','Vaucluse','Alpes-de-Haute-Provence','Hautes-Alpes'],answer:2,explanation:'Manosque se trouve dans les Alpes-de-Haute-Provence.'},
  {id:'sci1',category:'Sciences',difficulty:'Facile',type:'truefalse',question:'La Terre tourne autour du Soleil.',answer:true,explanation:'La Terre effectue une révolution autour du Soleil en un peu plus de 365 jours.'},
  {id:'sci2',category:'Sciences',difficulty:'Facile',type:'mcq',question:'Quel organe permet principalement de respirer ?',options:['Le foie','Les poumons','Les reins','L’estomac'],answer:1,explanation:'Les poumons assurent les échanges gazeux nécessaires à la respiration.'},
  {id:'sci3',category:'Sciences',difficulty:'Moyen',type:'mcq',question:'À quelle température l’eau pure gèle-t-elle à pression normale ?',options:['0 °C','10 °C','32 °C','100 °C'],answer:0,explanation:'À pression atmosphérique normale, l’eau pure gèle à 0 °C.'},
  {id:'sci4',category:'Sciences',difficulty:'Difficile',type:'mcq',question:'Quel est le symbole chimique de l’or ?',options:['Ag','Au','Or','Fe'],answer:1,explanation:'Le symbole chimique de l’or est Au, du latin aurum.'},
  {id:'anim1',category:'Animaux',difficulty:'Facile',type:'mcq',question:'Quel animal est le plus grand mammifère vivant ?',options:['Éléphant d’Afrique','Girafe','Baleine bleue','Rhinocéros blanc'],answer:2,explanation:'La baleine bleue est le plus grand animal connu vivant actuellement.'},
  {id:'anim2',category:'Animaux',difficulty:'Facile',type:'truefalse',question:'Les chauves-souris sont des mammifères.',answer:true,explanation:'Les chauves-souris sont bien des mammifères et allaitent leurs petits.'},
  {id:'anim3',category:'Animaux',difficulty:'Moyen',type:'mcq',question:'Quel animal peut dormir debout grâce à un système de verrouillage de ses membres ?',options:['Le cheval','Le chat','Le lapin','Le dauphin'],answer:0,explanation:'Le cheval peut se reposer debout grâce à son appareil de soutien des membres.'},
  {id:'hist1',category:'Histoire',difficulty:'Facile',type:'mcq',question:'Dans quel pays se trouvent les pyramides de Gizeh ?',options:['Mexique','Égypte','Grèce','Inde'],answer:1,explanation:'Les pyramides de Gizeh se trouvent en Égypte, près du Caire.'},
  {id:'hist2',category:'Histoire',difficulty:'Moyen',type:'numeric',question:'En quelle année a commencé la Révolution française ?',answer:1789,unit:'année',explanation:'La Révolution française commence en 1789.'},
  {id:'hist3',category:'Histoire',difficulty:'Moyen',type:'mcq',question:'Qui fut le premier homme à marcher sur la Lune ?',options:['Youri Gagarine','Buzz Aldrin','Neil Armstrong','Thomas Pesquet'],answer:2,explanation:'Neil Armstrong a été le premier homme à marcher sur la Lune en 1969.'},
  {id:'music1',category:'Musique',difficulty:'Facile',type:'mcq',question:'Combien de cordes possède une guitare classique standard ?',options:['4','5','6','8'],answer:2,explanation:'Une guitare classique standard possède six cordes.'},
  {id:'music2',category:'Musique',difficulty:'Moyen',type:'mcq',question:'Quel groupe a chanté « Bohemian Rhapsody » ?',options:['ABBA','Queen','U2','The Beatles'],answer:1,explanation:'« Bohemian Rhapsody » est une chanson du groupe Queen.'},
  {id:'music3',category:'Musique',difficulty:'Facile',type:'truefalse',question:'Un piano standard possède des touches blanches et noires.',answer:true,explanation:'Le clavier du piano alterne touches blanches et touches noires.'},
  {id:'cine1',category:'Cinéma & TV',difficulty:'Facile',type:'mcq',question:'Dans quel film trouve-t-on le personnage de Jack Sparrow ?',options:['Titanic','Pirates des Caraïbes','Avatar','Indiana Jones'],answer:1,explanation:'Jack Sparrow est le célèbre pirate de la saga Pirates des Caraïbes.'},
  {id:'cine2',category:'Cinéma & TV',difficulty:'Moyen',type:'mcq',question:'Comment s’appelle le sorcier à lunettes créé par J. K. Rowling ?',options:['Frodon','Merlin','Harry Potter','Gandalf'],answer:2,explanation:'Harry Potter est le héros de la saga créée par J. K. Rowling.'},
  {id:'cine3',category:'Cinéma & TV',difficulty:'Moyen',type:'truefalse',question:'Dans la série Friends, les personnages principaux sont six amis.',answer:true,explanation:'Friends suit principalement six amis : Rachel, Monica, Phoebe, Joey, Chandler et Ross.'},
  {id:'sport1',category:'Sport',difficulty:'Facile',type:'mcq',question:'Combien de joueurs une équipe de football aligne-t-elle sur le terrain au coup d’envoi ?',options:['9','10','11','12'],answer:2,explanation:'Une équipe de football commence normalement avec 11 joueurs sur le terrain.'},
  {id:'sport2',category:'Sport',difficulty:'Moyen',type:'mcq',question:'Dans quel sport utilise-t-on un volant ?',options:['Tennis','Badminton','Squash','Padel'],answer:1,explanation:'Le badminton se joue avec une raquette et un volant.'},
  {id:'sport3',category:'Sport',difficulty:'Facile',type:'truefalse',question:'Le Tour de France est une compétition cycliste.',answer:true,explanation:'Le Tour de France est l’une des plus célèbres courses cyclistes par étapes.'},
  {id:'food1',category:'Cuisine',difficulty:'Facile',type:'mcq',question:'Quel ingrédient est la base principale du guacamole ?',options:['Tomate','Avocat','Courgette','Concombre'],answer:1,explanation:'Le guacamole est préparé principalement à partir d’avocat.'},
  {id:'food2',category:'Cuisine',difficulty:'Moyen',type:'mcq',question:'De quel pays la pizza moderne est-elle originaire ?',options:['Espagne','France','Italie','Grèce'],answer:2,explanation:'La pizza moderne est associée à Naples, en Italie.'},
  {id:'food3',category:'Cuisine',difficulty:'Facile',type:'numeric',question:'Combien d’œufs y a-t-il dans une demi-douzaine ?',answer:6,unit:'œufs',explanation:'Une douzaine vaut 12, donc une demi-douzaine vaut 6.'},
  {id:'tech1',category:'Numérique',difficulty:'Facile',type:'mcq',question:'Quel symbole trouve-t-on obligatoirement dans une adresse email ?',options:['#','@','€','&'],answer:1,explanation:'Une adresse email contient obligatoirement le symbole @.'},
  {id:'tech2',category:'Numérique',difficulty:'Moyen',type:'mcq',question:'Quel raccourci clavier sert généralement à copier du texte sous Windows ?',options:['Ctrl + C','Ctrl + V','Ctrl + Z','Ctrl + P'],answer:0,explanation:'Ctrl + C sert à copier, tandis que Ctrl + V sert à coller.'},
  {id:'tech3',category:'Numérique',difficulty:'Facile',type:'truefalse',question:'Un mot de passe différent pour chaque compte améliore la sécurité.',answer:true,explanation:'Des mots de passe uniques limitent les conséquences si un compte est compromis.'},
  {id:'ins1',category:'Insolite',difficulty:'Facile',type:'mcq',question:'Quel animal a trois cœurs ?',options:['Le poulpe','Le dauphin','Le requin','La tortue'],answer:0,explanation:'Le poulpe possède trois cœurs.'},
  {id:'ins2',category:'Insolite',difficulty:'Moyen',type:'truefalse',question:'Les bananes sont naturellement légèrement radioactives.',answer:true,explanation:'Elles contiennent notamment du potassium-40, un isotope naturellement radioactif, à un niveau sans danger alimentaire.'},
  {id:'buzz1',category:'Culture générale',difficulty:'Facile',type:'buzzer',question:'Je suis jaune, je brille dans le ciel le jour et je chauffe la Terre. Qui suis-je ?',answerText:'Le Soleil',explanation:'Il s’agit du Soleil.'},
  {id:'buzz2',category:'Culture générale',difficulty:'Facile',type:'buzzer',question:'Je suis un instrument avec des touches blanches et noires. Qui suis-je ?',answerText:'Le piano',explanation:'La réponse attendue est le piano.'},
  {id:'buzz3',category:'Culture générale',difficulty:'Moyen',type:'buzzer',question:'Quel est le nom du satellite naturel de la Terre ?',answerText:'La Lune',explanation:'Le satellite naturel de la Terre est la Lune.'},
  {id:'cart1',category:'Dessins animés',difficulty:'Facile',type:'mcq',question:'Quel animal est Scooby-Doo ?',options:['Un chat','Un chien','Un cheval','Un lapin'],answer:1,explanation:'Scooby-Doo est un chien de race dogue allemand.'},
  {id:'cart2',category:'Dessins animés',difficulty:'Moyen',type:'mcq',question:'Comment s’appelle le père de la famille Simpson ?',options:['Ned','Homer','Moe','Barney'],answer:1,explanation:'Homer Simpson est le père de Bart, Lisa et Maggie.'},
  {id:'cart3',category:'Dessins animés',difficulty:'Difficile',type:'mcq',question:'Dans quel dessin animé trouve-t-on les personnages de Musclor et Skeletor ?',options:['Les Maîtres de l’Univers','Inspecteur Gadget','Les Schtroumpfs','Ulysse 31'],answer:0,explanation:'Musclor et Skeletor sont des personnages des Maîtres de l’Univers.'},
  {id:'game1',category:'Jeux vidéo',difficulty:'Facile',type:'mcq',question:'Quel personnage de Nintendo est un plombier moustachu vêtu de rouge ?',options:['Sonic','Mario','Link','Kirby'],answer:1,explanation:'Mario est le célèbre plombier de Nintendo.'},
  {id:'game2',category:'Jeux vidéo',difficulty:'Moyen',type:'truefalse',question:'Dans Minecraft, le monde est principalement construit à partir de blocs.',answer:true,explanation:'Minecraft repose sur un univers composé de blocs que le joueur peut casser et placer.'},
  {id:'game3',category:'Jeux vidéo',difficulty:'Difficile',type:'mcq',question:'Dans quelle série de jeux incarne-t-on souvent un héros nommé Link ?',options:['Final Fantasy','The Legend of Zelda','Metroid','Castlevania'],answer:1,explanation:'Link est le héros récurrent de la série The Legend of Zelda.'},
  {id:'lit1',category:'Littérature',difficulty:'Facile',type:'mcq',question:'Qui a écrit Les Misérables ?',options:['Émile Zola','Victor Hugo','Molière','Jules Verne'],answer:1,explanation:'Les Misérables est un roman de Victor Hugo.'},
  {id:'lit2',category:'Littérature',difficulty:'Moyen',type:'mcq',question:'Qui est l’auteur du Petit Prince ?',options:['Albert Camus','Antoine de Saint-Exupéry','Marcel Pagnol','Jean de La Fontaine'],answer:1,explanation:'Le Petit Prince a été écrit par Antoine de Saint-Exupéry.'},
  {id:'lit3',category:'Littérature',difficulty:'Difficile',type:'mcq',question:'Quel écrivain espagnol a créé le personnage de Don Quichotte ?',options:['Federico García Lorca','Miguel de Cervantes','Pablo Neruda','Lope de Vega'],answer:1,explanation:'Don Quichotte est le héros du roman de Miguel de Cervantes.'},
  {id:'myth1',category:'Mythologie',difficulty:'Facile',type:'mcq',question:'Quel dieu grec règne sur l’Olympe ?',options:['Hadès','Zeus','Hermès','Apollon'],answer:1,explanation:'Zeus est le roi des dieux de l’Olympe.'},
  {id:'myth2',category:'Mythologie',difficulty:'Moyen',type:'mcq',question:'Quel dieu nordique manie le marteau Mjöllnir ?',options:['Loki','Odin','Thor','Tyr'],answer:2,explanation:'Mjöllnir est le marteau de Thor.'},
  {id:'myth3',category:'Mythologie',difficulty:'Difficile',type:'buzzer',question:'Quelle créature mi-homme mi-taureau vivait dans le labyrinthe de Crète ?',answerText:'Le Minotaure',explanation:'Le Minotaure était enfermé dans le labyrinthe construit par Dédale.'},
  {id:'nature1',category:'Nature & environnement',difficulty:'Facile',type:'truefalse',question:'Les abeilles participent à la pollinisation de nombreuses plantes.',answer:true,explanation:'En transportant le pollen, les abeilles contribuent à la reproduction de nombreuses plantes.'},
  {id:'nature2',category:'Nature & environnement',difficulty:'Moyen',type:'mcq',question:'Quel gaz les plantes absorbent-elles principalement pendant la photosynthèse ?',options:['Oxygène','Dioxyde de carbone','Azote','Hélium'],answer:1,explanation:'Les plantes absorbent du dioxyde de carbone pendant la photosynthèse.'},
  {id:'nature3',category:'Nature & environnement',difficulty:'Difficile',type:'mcq',question:'Comment appelle-t-on la variété des êtres vivants et des écosystèmes ?',options:['La gravité','La biodiversité','La météorologie','La géologie'],answer:1,explanation:'La biodiversité désigne la diversité du vivant, des espèces aux écosystèmes.'},
  {id:'body1',category:'Corps humain',difficulty:'Facile',type:'mcq',question:'Quel organe fait circuler le sang dans le corps ?',options:['Le foie','Le cœur','Le poumon','Le rein'],answer:1,explanation:'Le cœur pompe le sang dans l’ensemble de l’organisme.'},
  {id:'body2',category:'Corps humain',difficulty:'Moyen',type:'mcq',question:'Quel est le plus grand organe du corps humain ?',options:['Le foie','La peau','Le cerveau','Le poumon'],answer:1,explanation:'La peau est le plus grand organe du corps humain.'},
  {id:'body3',category:'Corps humain',difficulty:'Difficile',type:'numeric',question:'Combien de paires de chromosomes possède normalement une cellule humaine ?',answer:23,unit:'paires',explanation:'Une cellule humaine possède normalement 23 paires de chromosomes.'},
  {id:'logic1',category:'Logique & devinettes',difficulty:'Facile',type:'numeric',question:'Quel nombre vient après 2, 4, 6 et 8 ?',answer:10,unit:'',explanation:'La suite augmente de 2 à chaque étape.'},
  {id:'logic2',category:'Logique & devinettes',difficulty:'Moyen',type:'buzzer',question:'Plus on m’enlève, plus je grandis. Qui suis-je ?',answerText:'Un trou',explanation:'En retirant de la matière, un trou devient plus grand.'},
  {id:'logic3',category:'Logique & devinettes',difficulty:'Difficile',type:'mcq',question:'Si tous les Nors sont des Vels et qu’aucun Vel n’est un Pim, un Nor peut-il être un Pim ?',options:['Oui, toujours','Non, jamais','Seulement parfois','On ne peut pas savoir'],answer:1,explanation:'Si aucun Vel n’est un Pim et que tous les Nors sont des Vels, aucun Nor ne peut être un Pim.'},
  {id:'art1',category:'Arts & peinture',difficulty:'Facile',type:'mcq',question:'Qui a peint La Joconde ?',options:['Claude Monet','Léonard de Vinci','Pablo Picasso','Vincent van Gogh'],answer:1,explanation:'La Joconde a été peinte par Léonard de Vinci.'},
  {id:'art2',category:'Arts & peinture',difficulty:'Moyen',type:'mcq',question:'Quel peintre a réalisé Guernica ?',options:['Pablo Picasso','Salvador Dalí','Paul Cézanne','Henri Matisse'],answer:0,explanation:'Guernica est une œuvre majeure de Pablo Picasso.'},
  {id:'art3',category:'Arts & peinture',difficulty:'Difficile',type:'mcq',question:'Quel sculpteur de la Renaissance a réalisé le David exposé à Florence ?',options:['Donatello','Michel-Ange','Le Bernin','Rodin'],answer:1,explanation:'Le célèbre David de Florence a été sculpté par Michel-Ange.'},
  {id:'lang1',category:'Langue française',difficulty:'Facile',type:'mcq',question:'Quel est le pluriel du mot « cheval » ?',options:['Chevals','Chevaux','Chevaus','Chevales'],answer:1,explanation:'Le pluriel de cheval est chevaux.'},
  {id:'lang2',category:'Langue française',difficulty:'Moyen',type:'mcq',question:'Quel mot est un synonyme de « rapide » ?',options:['Lent','Vif','Lourd','Calme'],answer:1,explanation:'Vif peut être employé comme synonyme de rapide.'},
  {id:'lang3',category:'Langue française',difficulty:'Difficile',type:'mcq',question:'Dans la phrase « Ils se sont parlé », comment s’écrit le participe passé ?',options:['Parlé','Parlés','Parlées','Parler'],answer:0,explanation:'Avec le verbe se parler, le pronom est complément indirect : le participe passé reste invariable.'},
  {id:'invent1',category:'Inventions & découvertes',difficulty:'Facile',type:'mcq',question:'Quel instrument sert à mesurer la température ?',options:['Un baromètre','Un thermomètre','Une boussole','Un chronomètre'],answer:1,explanation:'Le thermomètre sert à mesurer la température.'},
  {id:'invent2',category:'Inventions & découvertes',difficulty:'Moyen',type:'mcq',question:'Quel inventeur est associé à l’imprimerie à caractères mobiles en Europe ?',options:['Johannes Gutenberg','Louis Pasteur','Galilée','James Watt'],answer:0,explanation:'Johannes Gutenberg est associé au développement de l’imprimerie à caractères mobiles en Europe.'},
  {id:'invent3',category:'Inventions & découvertes',difficulty:'Difficile',type:'mcq',question:'Quel scientifique a découvert la pénicilline en 1928 ?',options:['Alexander Fleming','Marie Curie','Isaac Newton','Gregor Mendel'],answer:0,explanation:'Alexander Fleming a découvert les propriétés antibactériennes de la pénicilline en 1928.'},
  {id:'retro1',category:'Années 80, 90 & 2000',difficulty:'Facile',type:'mcq',question:'Quel appareil portable permettait d’écouter des cassettes audio avec un casque ?',options:['Le Walkman','Le Minitel','Le Polaroid','Le Tamagotchi'],answer:0,explanation:'Le Walkman a popularisé l’écoute nomade des cassettes audio.'},
  {id:'retro2',category:'Années 80, 90 & 2000',difficulty:'Moyen',type:'mcq',question:'Quel animal virtuel de poche est devenu un phénomène dans les années 1990 ?',options:['Le Tamagotchi','Le Furby','Le Walkman','Le Game Boy'],answer:0,explanation:'Le Tamagotchi est un animal virtuel de poche devenu très populaire dans les années 1990.'},
  {id:'retro3',category:'Années 80, 90 & 2000',difficulty:'Difficile',type:'numeric',question:'En quelle année est sorti le premier livre Harry Potter au Royaume-Uni ?',answer:1997,unit:'',explanation:'Harry Potter à l’école des sorciers a été publié au Royaume-Uni en 1997.'},
  {id:'world1',category:'Monde & cultures',difficulty:'Facile',type:'mcq',question:'De quel pays les sushis sont-ils originaires ?',options:['Chine','Japon','Thaïlande','Corée du Sud'],answer:1,explanation:'Les sushis sont associés à la cuisine japonaise.'},
  {id:'world2',category:'Monde & cultures',difficulty:'Moyen',type:'mcq',question:'Dans quel pays le tango s’est-il développé ?',options:['Argentine','Portugal','Mexique','Italie'],answer:0,explanation:'Le tango s’est développé notamment en Argentine, autour de Buenos Aires.'},
  {id:'world3',category:'Monde & cultures',difficulty:'Difficile',type:'mcq',question:'Quelle fête indienne est souvent appelée la fête des lumières ?',options:['Holi','Diwali','Hanami','Songkran'],answer:1,explanation:'Diwali est une grande fête indienne associée aux lumières.'}
];